<html>
<head>
<link rel="manifest" href="manifest.json">
<script
			  src="https://code.jquery.com/jquery-3.1.1.min.js"
			  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="
			  crossorigin="anonymous"></script>
</head>
<body>

<div class="registration">
Salut! Doresti sa primesti notificari despre stiri explozive?
<button id="abonare" class='notificare'>Da, te rog</button>
<button id="dezabonare" class='notificare'>Nu mai vreau notificari</button>
</div>

<div id="propertiesAlertPanel"></div>
<div id='subscription'>

</div>

<div class="send">
  <form>
  Notification delay: <input id='notification-delay' type='number' value='5'></input> seconds
  Notification Time-To-Live: <input id='notification-ttl' type='number' value='0'></input> seconds
  </form>

  <p>Either click this button to ask the server to send a notification: <button id="doIt">Try to conquer Italy!</button></p>
  <p>Or use <b>curl</b> on your command line to send the notification:</p>
  <span id="curl"></span>

  <p>N.B.: The curl command only works for push services implementing the Web Push standard (GCM, the push service used by Google Chrome, currently doesn't).</p>
</div>

<script>
$( document ).ready(function() {
  $('.send').hide();
var endpoint;

$(".notificare").click(function(){
  var idBtn = this.id;
  // Register a Service Worker.
  navigator.serviceWorker.register('app.js')
  .then(function(registration) {
    // Use the PushManager to get the user's subscription to the push service.
    return registration.pushManager.getSubscription()
    .then(function(subscription) {
      // If a subscription was found, return it.
      if (subscription) {
        return subscription;
      }

      // Otherwise, subscribe the user (userVisibleOnly allows to specify that we don't plan to
      // send notifications that don't have a visible effect for the user).
      return registration.pushManager.subscribe({ userVisibleOnly: true });
    });
  }).then(function(subscription) {
    console.log(subscription);
    endpoint = subscription.endpoint;
    if(idBtn == 'abonare') {
    var abonat = 1;
  } else {
    var abonat = 0;
  }
    var sub = JSON.stringify(subscription);

    $('#subscription').html("Endpoint: "+endpoint +  " <br/> obiect: "+ sub);



    // Show curl command to send the notification on the page.
    document.getElementById('curl').textContent = 'curl -H "TTL: 60" -X POST ' + endpoint;

    $.ajax({
               type: "POST",
               url: './register.php',
               data: { 'endpoint': endpoint, 'detalii': sub, 'abonat': abonat},
               success: function (data)
               {
                   $("#propertiesAlertPanel").html("<span style='color:darkgreen'>S-a salvat cu succes</span><br/>" +  data);
               }
           });


  });
});

});




document.getElementById('doIt').onclick = function() {
  var delay = document.getElementById('notification-delay').value;
  var ttl = document.getElementById('notification-ttl').value;

  // Ask the server to send the client a notification.
  // This is for testing purposes, in a real application the notifications will be
  // directly generated by the server without the user asking for it (otherwise, what
  // would be the point?).
  fetch('./sendNotification?endpoint=' + endpoint + '&delay=' + delay +
        '&ttl=' + ttl,
    {
      method: 'post',
    }
  );
};

</script>

</body>
</html>
